"""Add contribution column

Revision ID: 191c1e1713c4
Revises: a95247e2445f
Create Date: 2021-12-12 20:32:40.020596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191c1e1713c4'
down_revision = 'a95247e2445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contribution', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contribution')
    # ### end Alembic commands ###
