"""delete tag table

Revision ID: cf5ae246d999
Revises: b80ebd28364b
Create Date: 2021-12-03 01:23:30.793162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5ae246d999'
down_revision = 'b80ebd28364b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag', sa.VARCHAR(length=60), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('tag', 'post_id')
    )
    # ### end Alembic commands ###
